name: game_release_calendar
description: "A new Flutter project."

version: 1.0.1+6

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartx: ^1.2.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  flutter_bloc: ^8.1.6
  get_it: ^8.0.1
  package_info_plus: ^8.1.0
  spaced_flex: ^0.1.0
  riverpod: ^2.6.0
  freezed_annotation: ^3.0.0
  very_good_infinite_list: ^0.9.0
  hive_ce: ^2.10.2
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  dev: ^1.0.0
  custom_lint: ^0.8.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  permission_handler: ^11.3.1
  flutter_lucide: ^1.6.2
  shared_preferences: ^2.5.2
  flutter_toggle_tab: ^1.5.1
  connectivity_plus: ^6.1.0
  posthog_flutter: ^5.0.0
  toastification: ^2.3.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  flutter_lints: ^6.0.0
  pyramid_lint: ^2.4.0
  build_runner: ^2.0.0
  freezed: ^3.0.0
  json_serializable: ^6.0.1
  hive_ce_generator: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - env/env.json

import_sorter:
  comments: false